version: "3"
volumes:
  uploads:
  keys:
  db-data-0:
  db-data-1:
  db-data-2:
  db-data-3:

networks:
  frontend-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.10.12.0/24
        - subnet: 2001:3200:4200::/64
          gateway: 2001:3200:4200::1

  backend-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1

services:
  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/app"
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - api
    links: 
      - api
    networks:
      frontend-net:

  api:
    build: ./api
    volumes:
      - ./api:/app
      # - uploads:/app/uploads
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    depends_on:
      - mongo-primary
      - mongo-worker-1
      - mongo-worker-2
      - mongo-worker-3
    # network_mode: host
    networks: 
      frontend-net:
      backend-net:

  ## Mongo Database Backend
  mongo-keys:
    image: depop/openssl-bats
    volumes:
      - keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo-primary
      - DB_HOST=mongo-primary
    links:
      - mongo-primary
      - mongo-worker-1
      - mongo-worker-2
      - mongo-worker-3
    networks: 
      backend-net:

# Primary Node
  mongo-primary:
    image: mongo:latest
    volumes: 
      - keys:/opt/keyfile
      - db-data-0:/data/db
    env_file: .env
    # network_mode: host
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-replica-set'
    depends_on: 
      - mongo-keys
    networks: 
      backend-net:
  
# worker #1
  mongo-worker-1:
    image: mongo:latest
    volumes: 
      - keys:/opt/keyfile
      - db-data-1:/data/db
    env_file: .env
    # network_mode: host
    ports: 
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-replica-set'
    depends_on: 
      - mongo-keys
    networks: 
      backend-net:

# worker #2
  mongo-worker-2:
    image: mongo:latest
    volumes: 
      - keys:/opt/keyfile
      - db-data-2:/data/db
    env_file: .env
    # network_mode: host
    ports: 
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-replica-set'
    depends_on: 
      - mongo-keys
    networks: 
      backend-net:

# worker #3
  mongo-worker-3:
    image: mongo:latest
    volumes: 
      - keys:/opt/keyfile
      - db-data-3:/data/db
    env_file: .env
    # network_mode: host
    ports: 
      - 27020:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet db-replica-set'
    depends_on: 
      - mongo-keys
    networks: 
      backend-net: